on:
  - pull_request
  - push

jobs:
  test:
    name: Test library
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache-dependency-path: ./go.sum
          go-version-file: ./go.mod
          go-version: ">=1.12.0"
          check-latest: false
      - name: Install dependencies
        run: go get -v
      - name: Test all
        run: go test -v
